#!/bin/bash
set -e

. config
. ${PROGRAM}/script/build.sh

mkdir -p chroot
if [ ! -z ${USETMPFS} ];then
	mount -t tmpfs -o size=${USETMPFS},mode=0755 tmpfs chroot
fi

for MODULE in modules/??-*;do
	if [ -e ${MODULE}/build ];then
		Echo_message "build module: ${MODULE}"
		./${MODULE}/build
	fi
done
