#!/bin/bash
# This is a config file for Live Kit build script.
# Live Kit Name. Defaults to 'linux';
# This will be the name of the directory created on your CD/USB, which
# will contain everything including boot files and such.
LIVEKITNAME="linux"

# use tmpfs for build space. Use tmpfs will increase build time.
USETMPFS="8g"

# Kernel file, will be copied to your Live Kit
# Your kernel must support aufs and squashfs. 
VMLINUZ=/vmlinuz

# Kernel version. Change it to "3.2.28" for example, if you are building
# Live Kit with a different kernel than the one you are actually running
KERNEL=$(uname -r)

# List of directories for root filesystem
# No subdirectories are allowed, no slashes,
# so You can't use /var/tmp here for example
# Exclude directories like proc sys tmp
MKMOD="bin etc home lib lib64 opt root sbin srv usr var"

# If you require network support in initrd, for example to boot over PXE 
# you will need network modules included in your initrd.
# To disable, set to false will reduce initrd size
NETWORK=true

# Temporary directory to store livekit filesystem
LIVEKITDATA=/tmp/$LIVEKITNAME-data-$$

# Bundle extension, for example 'bundle' for .bundle extension
BEXT=bundle

# Directory with kernel .ko modules
LMK="lib/modules/$KERNEL"
