#!/bin/bash
# Create initramfs image
#
CHROOT=${CHROOT:-chroot/chroot}
INITRAMFS=${CHROOT}/root/initramfs.tmp

Chroot ()
{
	CHROOT="${1}"; shift
	COMMANDS="${@}"

	#TODO: we just use network environment
	ENV="$(grep -v '^network' config)"

	chroot "${CHROOT}" /usr/bin/env -i HOME="/root" PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin" ${ENV} ${COMMANDS}

	return "${?}"
}

rm -Rf $INITRAMFS

install -Dm755 initramfs/static/busybox $INITRAMFS/bin/busybox
install -Dm755 initramfs/static/eject $INITRAMFS/bin/eject
install -Dm755 initramfs/static/mount.dynfilefs $INITRAMFS/bin/@mount.dynfilefs
install -Dm755 initramfs/static/mount.httpfs2 $INITRAMFS/bin/@mount.httpfs2
install -Dm755 initramfs/static/mount.ntfs-3g $INITRAMFS/bin/@mount.ntfs-3g
install -Dm755 initramfs/static/blkid $INITRAMFS/bin/blkid

# chroot to install kernel module
install -Dm755 initramfs/initramfs_create_chroot ${CHROOT}/root/hooks/initramfs_create_chroot
Chroot ${CHROOT} /root/hooks/initramfs_create_chroot || { echo "chroot create initramfs failed.You should check for errors." >&2; exit 1; }

install -Dm755 initramfs/init $INITRAMFS/init
install -Dm755 initramfs/shutdown $INITRAMFS/shutdown
ln -s ../init $INITRAMFS/bin/init
install -Dm644 livekitlib $INITRAMFS/lib/
install -Dm644 config $INITRAMFS/lib/

cd $INITRAMFS
find . -print | cpio -o -H newc 2>/dev/null | xz -f --extreme --check=crc32 > ${OLDPWD}/initramfs.img
cd ${OLDPWD}

rm -Rf $INITRAMFS
