#!/bin/bash
set -e
. ${PROGRAM}/scripts/build.sh

DIST=${DIST:-testing}
ARCH=${ARCH:-amd64}
MIRROR=${MIRROR:-http://mirrors.ustc.edu.cn/debian}

Check_stagefile .build/bootstrap
mkdir -p chroot/01-base
debootstrap --arch=${ARCH} --no-check-gpg \
	${DIST} chroot/01-base ${MIRROR} 
Create_stagefile .build/bootstrap
