#!/bin/bash
set -e
. ${PROGRAM}/config
. ${PROGRAM}/scripts/build.sh

realpath=$(dirname `readlink -f $0`)
${realpath}/bootstrap

Require_stagefile .build/bootstrap
Check_stagefile .build/01-base
CHROOT=chroot/01-base ./scripts/build/chroot_misc install
CHROOT=chroot/01-base ./scripts/build/chroot_apt install
CHROOT=chroot/01-base ./scripts/build/chroot_dpkg-divert install

CHROOT=chroot/01-base ./scripts/build/chroot_miscfs install
Echo_message "Installing packages..."
Chroot chroot/01-base apt-get update
Chroot chroot/01-base apt-get ${APT_OPTIONS} install openssh-server linux-image-amd64
CHROOT=chroot/01-base ./scripts/build/chroot_miscfs remove

mkdir -p chroot/chroot
mkdir -p chroot/work

Create_stagefile .build/01-base
