#!/bin/bash
set -e
DIST=${DIST:-testing}
ARCH=${ARCH:-amd64}
MIRROR=${MIRROR:-http://mirrors.ustc.edu.cn/debian}

Check_stagefile .build/01-base

mkdir -p chroot/01-base
debootstrap --arch=${ARCH} --no-check-gpg \
	${DIST} chroot/01-base ${MIRROR} 

CHROOT=chroot/01-base ./scripts/build/chroot_misc install
CHROOT=chroot/01-base ./scripts/build/chroot_apt install
CHROOT=chroot/01-base ./scripts/build/chroot_dpkg-divert install

CHROOT=chroot/01-base ./scripts/build/chroot_miscfs install
Echo_message "Installing packages..."
Chroot chroot/01-base apt-get update
Chroot chroot/01-base apt-get install openssh-server
CHROOT=chroot/01-base ./scripts/build/chroot_miscfs remove

Create_stagefile .build/01-base

Check_stagefile .build/bootstrap
mkdir -p chroot/chroot
mkdir -p chroot/work
Create_stagefile .build/bootstrap
